version: '3'

services:
  chrome:
    image: lscr.io/linuxserver/chromium:latest
    container_name: cloud-browser

    security_opt:
      - seccomp:unconfined

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - CHROME_CLI=https://google.com

    ports:
      - "3000:3000"

    shm_size: "1gb"

    restart: unless-stopped