version: "3"

services:

  chromium:

    image: lscr.io/linuxserver/chromium:latest

    container_name: chromium

    security_opt:
      - seccomp:unconfined

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - CHROME_CLI=--remote-debugging-port=9222

    ports:
      - 3000:3000
      - 9222:9222

    shm_size: "1gb"
